### ISSUE TITLE
Autocomlete support for other languages

### ISSUE THREAD

**Issue by dimosthenes** [Uberi/Autocomplete#2]
I have added words to be used in wordlist (greek). how can the autocompletion work for these words as well?

**Comment by Uberi** [comment]
Hi @dimosthenes,

You can add/remove words in the settings dialog, as well as by editing the wordlist file itself. You may need to edit `NormalKeyList` in the top of the script file and in `Settings.ini` to make sure Greek-specific letters are supported properly.
