### ISSUE TITLE
Throws an error when called in URL bar (Firefox and Chrome)

### ISSUE THREAD

**Issue by dejavecue** [Uberi/Autocomplete#4]
Whenever you try to type something in the url bar of a browser, it throws this error.

![2015-12-18 10_24_42-autocomplete ahk](https://cloud.githubusercontent.com/assets/16348513/11893571/ea4e7292-a571-11e5-9c87-a5f8cae5d30a.png)

**Comment by Uberi** [comment]
Hi @dejavecue,

Can you insert the following immediately before line 295, and reproduce the error?

    If (PosX = "") {
        MsgBox, "%A_CaretX%" "%A_CaretY%" "%ScreenWidth%" "%ScreenHeight%"
    }

When you now run it again, there will be a MsgBox that pops up. Can you post that value in this issue (you can copy the contents of the MsgBox using Ctrl + C)?

**Comment by dejavecue** [comment]
---------------------------
Autocomplete.ahk
---------------------------
"" "" "3840" "1080"
---------------------------

This is the message. Then the usual error opens.
Could it be that I need to specifically set it up for my two monitors?

**Comment by Uberi** [comment]
Hi @dejavecue,

Can you try the latest version to see if it's fixed? You can [download it here](https://github.com/Uberi/Autocomplete/archive/master.zip).

**Comment by dejavecue** [comment]
Working a lot better now, thanks! 
However, in every firefox message box (and url bar), it now opens the suggestion window at the top left, where it is overlapped by the task bar.

![2015-12-21 07_42_02-search](https://cloud.githubusercontent.com/assets/16348513/11924920/99754750-a7b6-11e5-91f0-c833e8f0f572.png)

![Uploading 2015-12-21 07_42_02-Search.png…]()

However this is by far better than an error message.

**Comment by Uberi** [comment]
Hi @dejavecue,

Unfortunately this doesn't seem to be doable, as these browsers use custom controls that don't expose standard caret interfaces.

However, you can get around the overlapping taskbar by changing the `OffsetY := 20` line (line 15) in Autocomplete.ahk to a larger value, so that it shows up below the bar.

**Comment by dejavecue** [comment]
Thank you very much for your help. 
Now with this issue resolved, this thing is the most awesome thing for productivity.
Thank you.
